### ISSUE TITLE
Sprint 1 - Update

### ISSUE THREAD

**Issue by scharffc** [scharffc/citizee#42]
@citizee @BrightGardenStrategies 

I asked Kimson to send us a video and screenshots of the app on 3/23 for discussion. It will be good for visiblity. I will execute the app on my phone as soon as we have a iOS account.

The sprint 1 version of the app will have the following screens:
Splash, login, main screen, submit an incident screen (or screens), submit a sexual violence screen (or screens), list of reports and some other useful screens.

I will be in touch with Maria for the required art and with Peter for the process/management.

Please note that the app may not look the way we want it at first. We are making it happen first!

We will see how this goes.

**Comment by citizee** [comment]
..Understood.

**Comment by scharffc** [comment]
@citizee @BrightGardenStrategies

This means that there will be a meeting where Will will have to give feedback on the first version of the app from the video and screenshots.

**Comment by citizee** [comment]
next week (After Tuesday 3/17) I can come to Astoria
